
package pt.ipg.mcm.wct.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "cliente", targetNamespace = "http://services.mcm.ipg.pt/", wsdlLocation = "file:///Users/francisco/git/samples/MetradoCM/ws-client-tests/src/test/resources/wsdl/cliente.wsdl")
public class Cliente
    extends Service
{

    private final static URL CLIENTE_WSDL_LOCATION;
    private final static WebServiceException CLIENTE_EXCEPTION;
    private final static QName CLIENTE_QNAME = new QName("http://services.mcm.ipg.pt/", "cliente");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:///Users/francisco/git/samples/MetradoCM/ws-client-tests/src/test/resources/wsdl/cliente.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTE_WSDL_LOCATION = url;
        CLIENTE_EXCEPTION = e;
    }

    public Cliente() {
        super(__getWsdlLocation(), CLIENTE_QNAME);
    }

    public Cliente(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIENTE_QNAME, features);
    }

    public Cliente(URL wsdlLocation) {
        super(wsdlLocation, CLIENTE_QNAME);
    }

    public Cliente(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLIENTE_QNAME, features);
    }

    public Cliente(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Cliente(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClienteService
     */
    @WebEndpoint(name = "clientePort")
    public ClienteService getClientePort() {
        return super.getPort(new QName("http://services.mcm.ipg.pt/", "clientePort"), ClienteService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClienteService
     */
    @WebEndpoint(name = "clientePort")
    public ClienteService getClientePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.mcm.ipg.pt/", "clientePort"), ClienteService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTE_EXCEPTION!= null) {
            throw CLIENTE_EXCEPTION;
        }
        return CLIENTE_WSDL_LOCATION;
    }

}
