
package pt.ipg.mcm.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClienteService", targetNamespace = "http://services.mcm.ipg.pt/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClienteService {


    /**
     * 
     * @param arg0
     * @return
     *     returns pt.ipg.mcm.client.ResGetCliente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCliente", targetNamespace = "http://services.mcm.ipg.pt/", className = "pt.ipg.mcm.client.GetCliente")
    @ResponseWrapper(localName = "getClienteResponse", targetNamespace = "http://services.mcm.ipg.pt/", className = "pt.ipg.mcm.client.GetClienteResponse")
    @Action(input = "http://services.mcm.ipg.pt/ClienteService/getClienteRequest", output = "http://services.mcm.ipg.pt/ClienteService/getClienteResponse")
    public ResGetCliente getCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        ReqGetCliente arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns pt.ipg.mcm.client.ResAddCliente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addCliente", targetNamespace = "http://services.mcm.ipg.pt/", className = "pt.ipg.mcm.client.AddCliente")
    @ResponseWrapper(localName = "addClienteResponse", targetNamespace = "http://services.mcm.ipg.pt/", className = "pt.ipg.mcm.client.AddClienteResponse")
    @Action(input = "http://services.mcm.ipg.pt/ClienteService/addClienteRequest", output = "http://services.mcm.ipg.pt/ClienteService/addClienteResponse")
    public ResAddCliente addCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        ReqAddCliente arg0);

}
