
package pt.ipg.mcm.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClienteService", targetNamespace = "http://services.mcm.ipg.pt/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClienteService {


    /**
     * 
     * @param request
     * @return
     *     returns pt.ipg.mcm.client.ResGetCliente
     */
    @WebMethod(operationName = "get-cliente")
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "get-cliente", targetNamespace = "http://services.mcm.ipg.pt/", className = "pt.ipg.mcm.client.GetCliente")
    @ResponseWrapper(localName = "get", targetNamespace = "http://services.mcm.ipg.pt/", className = "pt.ipg.mcm.client.Get")
    @Action(input = "http://services.mcm.ipg.pt/ClienteService/get-clienteRequest", output = "http://services.mcm.ipg.pt/ClienteService/get-clienteResponse")
    public ResGetCliente getCliente(
        @WebParam(name = "request", targetNamespace = "")
        ReqGetCliente request);

    /**
     * 
     * @param request
     * @return
     *     returns pt.ipg.mcm.client.ResAddCliente
     */
    @WebMethod(operationName = "add-cliente")
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "add-cliente", targetNamespace = "http://services.mcm.ipg.pt/", className = "pt.ipg.mcm.client.AddCliente")
    @ResponseWrapper(localName = "add", targetNamespace = "http://services.mcm.ipg.pt/", className = "pt.ipg.mcm.client.Add")
    @Action(input = "http://services.mcm.ipg.pt/ClienteService/add-clienteRequest", output = "http://services.mcm.ipg.pt/ClienteService/add-clienteResponse")
    public ResAddCliente addCliente(
        @WebParam(name = "request", targetNamespace = "")
        ReqAddCliente request);

}
